### ISSUE TITLE
Generators for views/models/controls does not work for ts-app

### ISSUE THREAD

**Issue by tapsiturbi** [ui5-community/generator-ui5-project#12]
## Easy-Ui5 version:
3.0.1

## OS/version:
Windows 10

## Browser/version (+device/version):
Chrome
## Steps to reproduce the problem:

1. yo easy-ui5 ts-app
2. cd com.myorg.myapp/
3. yo easy-ui5 project newview

## What is the expected result?
Module automatically found and yo should continue to ask questions about view to generate

## What happens instead?
Screen stuck with message and user cannot do anything:
`? To which module do you want to add a view? (Use arrow keys)`

## Any other information? (attach screenshot if possible)
![2021-07-25_12-34-44](https://user-images.githubusercontent.com/5230399/126887880-ceef2669-1ae8-4c96-b8a4-023ed583bf30.png)

**Comment by IObert** [comment]
It seems like you want to combine subgenerators of different plugins (generator-ui5-project and generator-ui5-ts-app). 
This is not possible, which is why this fails in your case. The subgenerators (of generator-ui5-project) for new views/models/controls are only supposed to work in projects that were generated which generator-ui5-project.

I'm mentioning @petermuessig here so that he's aware of this thread and might want to consider adding subgenerators to generator-ui5-ts-app as well. Or maybe you want to open a PR to add these features.

**Comment by tapsiturbi** [comment]
Thanks @IObert . My bad, I didn't know the ts-app was a separate plugin. I'll look at that and tweak it for our needs instead. Thanks!
